//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimonMaxime_Evaluation1_453
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        public int ProduitID { get; set; }
        public string NomProduit { get; set; }
        public Nullable<int> CategorieID { get; set; }
        public string QuantiteParUnite { get; set; }
        public Nullable<decimal> PrixUnite { get; set; }
        public Nullable<short> UnitesEnStock { get; set; }
        public Nullable<short> UnitesSurCommande { get; set; }
        public bool Discontinu { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
